# Generated by Django 6.0.4 on 2026-08-17 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150, verbose_name='اسم المرسل')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('sender_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('read', 'مقروءة'), ('archived', 'مؤرشفة')], default='new', max_length=20, verbose_name='حالة الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل الواردة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2025', max_length=50, verbose_name='السنة / الفترة الزمنية')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى / المحطة')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='الجهة / المنظمة')),
                ('description', models.TextField(verbose_name='تفاصيل الإنجاز والخبرة')),
                ('icon', models.CharField(default='mdi-briefcase', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#7B6EF6', max_length=30, verbose_name='اللون المميز')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'خبرة مهنية',
                'verbose_name_plural': 'الخبرات والخط الزمني',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='الملف')),
                ('file_type', models.CharField(default='image', max_length=50, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف بالبايت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'مكتبة الوسائط',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='عبد الخالق الصايدي', max_length=150, verbose_name='الاسم الكامل')),
                ('title', models.CharField(default='مطور Full Stack', max_length=150, verbose_name='المسمى الوظيفي')),
                ('tagline', models.CharField(default='أبني أنظمة قابلة للتوسع وواجهات أنيقة تُشحن للإنتاج.', max_length=255, verbose_name='الشعار / العبارة التعريفية')),
                ('bio', models.TextField(default='ثلاث سنوات من شحن أنظمة مؤسسية معقدة وتطبيقات ويب عالية الأداء في بيئات إنتاجية حقيقية باستخدام Vue 3 وDjango وPostgreSQL.', verbose_name='نبذة عني')),
                ('email', models.EmailField(default='abdul.khaliq.al.saidi@gmail.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='+967 771 523 243', max_length=30, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(default='967771523243', max_length=30, verbose_name='رقم الواتساب')),
                ('github', models.URLField(default='https://github.com', verbose_name='رابط GitHub')),
                ('linkedin', models.URLField(default='https://linkedin.com', verbose_name='رابط LinkedIn')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='رابط منصة X/Twitter')),
                ('location', models.CharField(default='اليمن', max_length=100, verbose_name='الموقع الجغرافي')),
                ('avatar', models.CharField(default='/avatar.jpg', max_length=500, verbose_name='رابط صورة الملف الشخصي')),
                ('resume', models.CharField(default='/resume.pdf', max_length=500, verbose_name='رابط ملف السيرة الذاتية (PDF)')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='متاح للعمل الحر والتوظيف')),
                ('years_of_experience', models.PositiveIntegerField(default=3, verbose_name='سنوات الخبرة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملف الشخصي',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرف اللطيف (Slug)')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('short_description', models.TextField(verbose_name='وصف مختصر')),
                ('full_description', models.TextField(blank=True, verbose_name='الوصف الكامل للمشروع')),
                ('problem', models.TextField(blank=True, verbose_name='المشكلة والتحدي')),
                ('architecture', models.TextField(blank=True, verbose_name='المعمارية والحل البرمجي')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='أبرز مميزات المشروع')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='التقنيات المستخدمة')),
                ('image', models.CharField(default='https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', max_length=500, verbose_name='رابط الصورة الرئيسية')),
                ('demo_url', models.CharField(blank=True, default='https://demo.example.com', max_length=500, verbose_name='رابط المعاينة الحية')),
                ('github_url', models.CharField(blank=True, default='https://github.com', max_length=500, verbose_name='رابط GitHub')),
                ('accent_color', models.CharField(default='#7B6EF6', max_length=30, verbose_name='اللون التمييزي للمشروع')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مشروع مميز (Featured)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور في الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('icon', models.CharField(default='mdi-monitor-dashboard', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#7B6EF6', max_length=30, verbose_name='اللون المميز')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='مميزات الخدمة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='مفتاح الإعداد')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
                ('group_name', models.CharField(default='general', max_length=50, verbose_name='المجموعة')),
                ('setting_type', models.CharField(default='text', max_length=20, verbose_name='نوع الحقل')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الإعداد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد عام',
                'verbose_name_plural': 'إعدادات الموقع العامة',
                'ordering': ['group_name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('icon', models.CharField(default='mdi-code-braces', max_length=50, verbose_name='أيقونة التصنيف')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف مهارات',
                'verbose_name_plural': 'تصنيفات المهارات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='العنوان التوضيحي')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='القيمة الرقمية')),
                ('suffix', models.CharField(blank=True, default='+', max_length=10, verbose_name='اللاحقة (مثل + أو %)')),
                ('icon', models.CharField(default='mdi-rocket-launch', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#7B6EF6', max_length=30, verbose_name='اللون')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'إحصائية',
                'verbose_name_plural': 'الإحصائيات والأرقام',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='اسم العميل')),
                ('client_role', models.CharField(max_length=150, verbose_name='المنصب والشركة')),
                ('client_company', models.CharField(blank=True, max_length=150, verbose_name='اسم الشركة')),
                ('client_avatar', models.CharField(blank=True, max_length=500, verbose_name='صورة العميل')),
                ('feedback_text', models.TextField(verbose_name='نص الشهادة والتقييم')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='التقييم (1-5)')),
                ('color', models.CharField(default='rgba(123,110,246,0.2)', max_length=50, verbose_name='لون الخلفية التمييزي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء وشهادات العملاء',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('entity_type', models.CharField(max_length=100, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الكيان')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل رقابة',
                'verbose_name_plural': 'سجلات الرقابة والعمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='رابط الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف توضيحي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'صورة للمشروع',
                'verbose_name_plural': 'معرض صور المشاريع',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهارة / التقنية')),
                ('icon', models.CharField(default='mdi-code-tags', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#7B6EF6', max_length=30, verbose_name='لون العلامة')),
                ('proficiency_percentage', models.PositiveIntegerField(default=85, verbose_name='نسبة الإتقان (%)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر في الموقع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مهارة تقنية',
                'verbose_name_plural': 'المهارات التقنية',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
