# Generated by Django 6.0.4 on 2026-08-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='أنظمة مؤسسية (ERP)', max_length=150, verbose_name='تصنيف أو نطاق المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.JSONField(blank=True, default=list, verbose_name='النتائج والقياس الفعلي'),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.JSONField(blank=True, default=list, verbose_name='الأهداف الهندسية المحددة'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='Lead Full Stack Engineer', max_length=150, verbose_name='الدور الهندسي'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, default='2025', max_length=50, verbose_name='سنة التنفيذ'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description',
            field=models.CharField(blank=True, default='تم تطويرها واختبارها وفق معايير الجودة والأمان.', max_length=255, verbose_name='الوصف التوضيحي'),
        ),
    ]
