# Generated by Django 6.0.4 on 2026-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_category_project_metrics_project_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='behance',
            field=models.URLField(blank=True, default='', verbose_name='رابط Behance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dribbble',
            field=models.URLField(blank=True, default='', verbose_name='رابط Dribbble'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='', verbose_name='رابط Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='رابط الموقع / المعرض الشخصي'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, default='', verbose_name='رابط YouTube'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_for_work',
            field=models.BooleanField(default=True, verbose_name='متاح للعمل الحر والمشاريع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default='https://github.com', verbose_name='رابط GitHub / المستودع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com', verbose_name='رابط LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط ملف السيرة الذاتية (PDF)'),
        ),
    ]
