# Generated by Django 6.0.4 on 2026-08-25 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_behance_profile_dribbble_profile_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('version', models.CharField(default='1.0.0', max_length=30, verbose_name='إصدار القالب')),
                ('import_mode', models.CharField(choices=[('CREATE_ONLY', 'إنشاء الجديد فقط'), ('UPSERT', 'تحديث أو إنشاء'), ('SKIP_EXISTING', 'تجاهل الموجود'), ('REPLACE', 'استبدال شامل')], default='UPSERT', max_length=30, verbose_name='طريقة الاستيراد')),
                ('status', models.CharField(choices=[('SUCCESS', 'ناجح'), ('FAILED', 'فشل'), ('PARTIAL', 'جزئي'), ('VALIDATING', 'قيد الفحص')], default='SUCCESS', max_length=20, verbose_name='حالة العملية')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='إحصائيات الكيانات')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='العناصر المنشأة')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='العناصر المحدثة')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='العناصر المتخطاة')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحذيرات')),
                ('errors_log', models.JSONField(blank=True, default=list, verbose_name='سجل تفاصيل الأخطاء')),
                ('warnings_log', models.JSONField(blank=True, default=list, verbose_name='سجل تفاصيل التحذيرات')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدة التنفيذ (مللي ثانية)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ وتوقيت العملية')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ')),
            ],
            options={
                'verbose_name': 'سجل استيراد بيانات',
                'verbose_name_plural': 'سجل عمليات استيراد البيانات',
                'ordering': ['-created_at'],
            },
        ),
    ]
