# Generated by Django 6.0.4 on 2026-08-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataimporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الجهة / المنظمة'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.CharField(default='', max_length=50, verbose_name='السنة / الفترة الزمنية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='نبذة عني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default='', verbose_name='رابط GitHub / المستودع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='رابط LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الشعار / العبارة التعريفية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الواتساب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True, default='', verbose_name='المعمارية والحل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='تصنيف أو نطاق المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط المعاينة الحية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='الوصف الكامل للمشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط GitHub / المستودع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='objectives',
            field=models.JSONField(blank=True, default=list, verbose_name='الأهداف المحددة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, default='', verbose_name='المشكلة والتحدي'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='الدور المهني / الهندسي'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='التقنيات / الأدوات المستخدمة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='سنة التنفيذ'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف التوضيحي'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_avatar',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='صورة العميل'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_company',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الشركة'),
        ),
    ]
