# Generated by Django 6.0.4 on 2026-08-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_experience_organization_alter_experience_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='after_image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='صورة بعد التنفيذ (After)'),
        ),
        migrations.AddField(
            model_name='project',
            name='after_notes',
            field=models.JSONField(blank=True, default=list, verbose_name='مخرجات وحلول الوضع بعد التطوير'),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_stages',
            field=models.JSONField(blank=True, default=list, verbose_name='مراحل المعمارية ومسار العمل'),
        ),
        migrations.AddField(
            model_name='project',
            name='before_image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='صورة قبل التنفيذ (Before)'),
        ),
        migrations.AddField(
            model_name='project',
            name='before_notes',
            field=models.JSONField(blank=True, default=list, verbose_name='ملاحظات وتحديات الوضع السابق'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='اسم العميل / الشريك'),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_quote',
            field=models.TextField(blank=True, default='', verbose_name='اقتباس أو شهادة العميل'),
        ),
    ]
