# Generated by Django 6.0.4 on 2026-08-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_after_image_project_after_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='الرابط الدائم (Slug)')),
                ('category', models.CharField(default='عام', max_length=100, verbose_name='التصنيف / التخصص')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='المقتطف / النبذة المختصرة')),
                ('content', models.TextField(verbose_name='محتوى المقال (Markdown / Rich Text)')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='صورة الغلاف')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='الوسوم والكلمات المفتاحية')),
                ('reading_time_minutes', models.PositiveIntegerField(default=3, verbose_name='وقت القراءة المقدر (بالدقائق)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقال مميز')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور في الموقع')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان الـ SEO (Meta Title)')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='وصف الـ SEO (Meta Description)')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='الكلمات المفتاحية للـ SEO')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مقال / تدوينة',
                'verbose_name_plural': 'المدونة والمقالات',
                'ordering': ['-is_featured', 'sort_order', '-published_at'],
            },
        ),
    ]
