# Generated by Django 6.0.4 on 2026-08-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
        migrations.AddField(
            model_name='experience',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية ديناميكية'),
        ),
    ]
