# Generated by Django 6.0.4 on 2026-09-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_dynamic_extra_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.CharField(blank=True, default='mdi-star-four-points', max_length=500, verbose_name='شعار أو أيقونة الموقع (Logo)'),
        ),
    ]
